Clifton Strengths and Data Analytics
The results of my Clifton Strengths assessment list my top five categorical strengths as follows: Relator, Belief, Intellection, Learner, and Deliberative. I find these to be incredibly accurate. This paper will include a self-reflection of the advantages and disadvantages of my top five categorical strengths, a snapshot and comparison of three data analyst roles, and a brief analysis of how I can use these strengths as assets to become a data scientist.
A.   PDF Copy of My Clifton Assessment "Signature Themes" Report (Attached)
1.  My Clifton Strengths Assessment Self-Reflection
Relator 
	I have a history of maintaining a few, yet meaningful friendships. I value understanding the details of a few people over having more friendships with less depth. I prefer socializing one-on-one or within a small, close-knit group. This strength can become a weakness at times when I’m in larger class settings, or beginning a new class, project, or activity. I can be slow to warm up to strangers, but I do easily connect to people once we get to know one another. 
	Using the action items in the Clifton Strengths for Students report, I can apply and maximize my strength as a relator by making time to meet one-on-one with new people, finding a role where I can mentor someone, or making a list of my best supporters. Others tend to rely on me because I am responsible, loyal, and trustworthy. Friends and associates depend on me for direction, advice, and listening to them when they are struggling with an issue. I can further maximize my strength as a relator by developing new friendships and reaching out to people that I connect with. 
Belief 
	I have core values that define my purpose in life. I ensure that the plans, activities, and choices that I make align with my beliefs. However, I am also open-minded regarding other people’s values and am empathetic towards differing perspectives. I could see this strength getting in the way of group projects if it requires sacrificing my values. I do know how to persevere despite the challenge, while wrestling with external and internal tensions. 
	My core values are honesty, authenticity, and dependability. I am determined to prioritize the values throughout my educational journey as well as in my career. I aim to look for these values in others as well. I can look for online groups that hold similar beliefs during my educational journey to help myself thrive while in school. I can help others find their value by pointing them to a core principle or value to keep them on track.
	Some core or unchanging beliefs that consistently show up in my life as a student, as mentioned above, are honesty, authenticity, and dependability. I decide whether something aligns or clashes with my values by contextualizing the idea or action to the person and measuring it against my core values. For example, if someone is relaying a story about a family member who was arrested for stealing items from a grocery store, I take time to understand that person’s life situation before judging my peer’s family member. 
Intellection 
	I am introspective and often find myself deep in thought. I also tend to seek out intellectual content and discussions within my educational, personal, and professional pursuits. I have an internal dialogue that makes me, at times, come off as distracted or aloof. I do not accept superficial information and have a difficult time in environments in which I am required to listen to unnecessary knowledge. I need context, details, and meaning in conversations, educational content, and interactions to make sense of them. I analyze decisions thoroughly to enrich information intake. This strength has the tendency to make me appear quiet or disinterested in group settings. I do not like to be put on the spot because I need time to think before I speak. Having to think and process information can lead me to procrastinate when starting projects or assignments.
	I can use this strength to make the most of my educational journey by putting aside as much time as possible for my studies. I love learning new information; however, due to my increased need to know details and desire for extensive analysis, I require more time to learn than others. I can take advantage of class outlines and syllabi to get an idea of what each course is about, to deepen the excitement and lessen the anxiety. I have found that Microsoft’s OneNote app is a great application for me to take notes and categorize course material. I have made a habit of making a thought dump to help lessen the content within my internal dialogue as I learn new material. I could also reach out to others who are in the MSDA program through WGU Connect or something similar, to bounce ideas off one another. 
	I think freely in a quiet space with minimal noise and headphones. This is my ideal setup for studying. I can safely share my questions and thoughts with my husband as well as a couple of friends. I have a blog that I need to update more frequently, and a couple of social media groups that I can participate in. 
Learner 
	For years, I have labeled myself as a lifelong learner. I love to learn; however, it is difficult for me to do so in an unstructured fashion. This has led me to obtain multiple college degrees in subjects that I am interested in and can apply to my personal life; however, not as much in a professional manner. I love school supplies, new tech, notebooks, and textbooks. This love for learning has led me to lead small group studies and teach a class at church. 
	I tend to get frustrated in large classrooms. I learn best when participating in small groups that have discussions or when I am by myself. I have faced difficulties when having to work in groups where other participants were not willing to pull their weight. In the past, this caused me to have a fight-or-flight response. As I have dealt with more of these experiences over time, I learned to communicate my frustrations and how to get others involved. 
	I picked the MSDA program because it excites and challenges me. I love to learn new skills and to analyze information. My problem is that I learn for fun, which eliminates having other hobbies. I find it difficult to sacrifice the time that I have available for learning to do something that does not require working towards an educational or professional goal. I do enjoy building relationships, and being intentional about learning something new about the people in my life helps to fill my desire for growth and knowledge. Even though I am on a hiatus from teaching at church, I know that I thrive when I can mentor or teach others. 
 	I can focus my learning right now on working on the two performance assessments for this class and allowing the information that is provided to permeate my mind. This would help me to reach goals by acquiring this foundational information to set a precedent for the rest of my degree program. My learning process consists of familiarizing myself with the class outline, keeping organized notes, prioritizing a study schedule, and making other people aware of my schedule to mitigate distractions and continual last-minute changes. 
Deliberative 
While I have never thought to use this adjective to describe my strength, deliberative is a suiting descriptor for me. I do think thoroughly through choices when making decisions, and prepare for things not to go as planned. I research the most minute decisions. For example, the recent decision of which USB-C cable is the best option. This decision is inexpensive and inconsequential. I help others think thoroughly through their problems as well. 
	I have an overarching internal tension that I never have enough time to learn to the extent that I desire. I find it difficult to make decisions without knowing all the options or information involved. I do my best critical thinking alone and find it more difficult if I am in a group setting with time restraints. I have found that setting deadlines helps when studying independently. I should make a point to ask teachers and peers questions more often, to think from a different perspective when I become stuck. If others knew how I do my best thinking, it would take the pressure off and perhaps allow me to increase my participation by feeling understood 
My most meaningful educational goal is to acquire proficiency in the MSDA program to be a prize candidate for an organization that aligns with my passions and values. I will use my strengths to reach this goal by networking (Relator), holding true to my values (Belief), focusing my introspection (Intellect), pursuing my love of learning (Learner), while feeling confident about my decision, choice of study, and career (Deliberative). I will know that I have been successful when I find a job that suits my skill set. 
B.  The Data Analyst, Business Intelligence Analyst, and Data Scientist
The Role of the Data Analyst
	The data analyst creates dashboards and reports that present data. The analyst collects data within an organization, formats and arranges the data effectively, and shows the results to stakeholders. This involves a lot of data cleaning and preprocessing. The work also includes creating automated, meaningful visualizations that are visually compelling and easy to understand. The analyst is also responsible for transforming data appropriately to suit the demands of the business question. (Robinson & Nolis, 2020)
The Role of the Business Intelligence Analyst
	The business intelligence (BI) analyst uses data primarily to help businesses navigate daily decisions. The BI analyst monitors and helps stakeholders to visualize data effectively by gathering and organizing datasets such as revenue, sales, market trends, or customer engagement metrics. The BI analyst finds trends and patterns that correlate to areas of improvement, and shares and presents data through graphs, charts and reports. They are responsible for reporting, forecasting, creating dashboards, data analysis, data collection, and data governance. (WGU, 4.1.1)
The Role of the Data Scientist
	Data scientists, like data analysts, spend a lot of time cleaning and preparing data. They also have the added requirements of making statistical models, coding with programming languages such as Python and/or R, and training machine learning models. Drew Conway created a Venn Diagram that defines the role of a data scientist. It consists of being proficient in math and statistics, coding, and knowledge of a domain. Robinson & Nolis soften Conway’s definition by requiring expertise in at least one of the three areas instead of all of them, with the caveat that fundamental knowledge of all three skills is, however, necessary. (Robinson & Nolis, 2020)
1.	Differences Between the Three Roles
Data Science vs Data Analysis
Data scientists focus on providing insights to people that are not yet known. These insights are strategic and actionable. These insights identify a trend or a future technology that does not yet exist but will have a significant effect on the organization in the time to come. (Project Pro, 2024). Data scientists, succinctly put, interpret data. They need to find out what the data reveals and deduce how these insights will benefit the company. This usually involves using statistical methods with programming languages.
Data analysts, compared to data scientists, also make predictions. However, data analysts focus on correlational analysis among relationships between data sets to predict future outcomes. Data analysts are not required to possess a broad understanding of how businesses operate and have a narrower focus compared to data scientists. (Project Pro, 2024). While data analysts do rely on statistical measures to explore data, data scientists provide more advanced statistical methods due to their heavy reliance on programming languages such as Python and R. 
Data Science vs Business Intelligence
Business intelligence (BI) analysts assess trends and patterns to help a business improve and become more profitable. BI Analysts organize and gather data to help organizations understand KPIs. These analysts are at a deficit in adapting to AI due to a lack of the data science techniques needed to decipher unstructured data types. BI analysts also lack a programming schoolhouse, which subsequently includes having the know-how when it comes to decision science, presentations, insights extraction, business consulting, and process optimization. (WGU, 4.1.1)
Data Analytics vs Business Intelligence Analytics vs Data Science
	 The business intelligence (BI) analyst role is a good entry position to becoming a data scientist. The BI analyst is like the data analyst role, except the BI analyst does not do machine learning, programming, or handling of statistical methods. A BI analyst may likely use Excel instead of a programming language like Python. This is simply because they do not typically deal with statistical models. The tools and techniques of a BI analyst are generally more limited, with less sophisticated output than that of a data analyst. (Robinson & Nolis, 2020)
1.	Academic Skills Needed for Three Roles 
Academic Skills Needed for a Data Analyst
According to a Coursera article, the seven in-demand skills that will get you hired in 2025 are: SQL, statistical programming languages like R or Python, machine learning, probability and statistics, data management, statistical visualization, and econometrics (Coursera Staff, April 2025). Data visualization tools such as Tableau and Power BI are also needed in data analysis. Soft skills include having effective communication in data storytelling, presentation skills, and interpersonal skills; advanced problem-solving abilities in critical thinking, analytical reasoning, and innovation; attention to detail in data cleaning, quality assurance, and documentation. The educational pathways can range from online bootcamps, bachelor’s degrees, and post-grad degrees (Crabtree, 2024).
Academic Skills Needed for a Business Intelligence Analyst
	The defining skills for a BI Analyst according to the NCSU website are Data Analysis Expressions, Tableau, SQL, Statistics, Power BI, Python, Finance, Data Visualization, Data Modeling, Computer Science, Dashboard, Business Intelligence, and Data Analysis (NCSU, 2025). DataCamp states that programming in languages such as Python and R is not required; however, it can be valuable for advanced data analytics. Recommended soft skills for BI analysts are communication, problem-solving, attention to detail, teamwork, and collaboration. A bachelor’s degree in computer science, information technology, or a similar discipline is often a requirement. (Bothma, 2023). 
Academic Skills Needed for a Data Scientist
	Data scientists typically need to have a college education in mathematics, statistics, computer science, or in some type of STEM field. Employers typically prefer at least a bachelor’s degree, with some only electing candidates with post-graduate degrees (US Bureau of Labor Statistics (BLS), 2025). Essential skills for a data scientist include programming, statistics and probability, data wrangling and database management, machine learning and deep learning, data visualization, cloud computing, and interpersonal skills (Coursera Staff, May 2025). 
1.	Describe how each role from part B supports the data analytics life cycle.
The Data Analyst and the Data Analytics Life Cycle
	A data analyst supports the data analytics life cycle with data collection, data cleaning and preprocessing, data analysis, data visualizations and reporting, predictive analysis, data-driven decision-making, and continuous improvement. Their primary goal is to interpret data sets to improve business decisions and outcomes (WGU, 4.1.1). They support each phase of the data analytics life cycle from business understanding to reporting and visualization. In short, data analysts create dashboards and reports that deliver data (Robinson & Nolis, 2020).  
The Business Intelligence Analyst and the Data Analytics Life Cycle
	The BI Analyst supports the data analytics life cycle with reporting, forecasting, dashboard creation, data analysis, data collection, and data governance (WGU, 4.4.1). Of the three data analyst roles that I briefly discussed, this would be the role that is the least supportive of the data analytics life cycle in its entirety. Looking at various sources, I found that the role of the BI analyst varies the most. Robinson and Nolis state that the BI analyst does not require much machine learning, programming, or statistical methods, and that it is a great entry role into the data scientist field (Robinson and Nolis, 2020). While another source states that these skills are required, the BI analyst has the least amount of data analytics skills required. The phases that BI analysts are least likely to support are predictive modeling and data mining. They likely support the remaining phases closest to the data analyst and far less than the data scientist. 
 The Data Scientist and the Data Analytics Life Cycle
	The Data Scientist supports the data analytics life cycle with data analysis, data visualization, data cleaning, A/B testing, machine learning, data storytelling, collaboration, experimentation, and continuous improvement (WGU, 4.4.1). Data scientists use data to try to solve and understand real-world problems and are required to be experts in at least math and statistics, programming, and databases, or domain knowledge, if not in all three. Data scientists support each phase of the life cycle and excel in the reporting and visualization phase. They could be viewed as trend setters. Data scientists create trends and technology that historical data does not yet exist.
C. Career Goal Based on Strengths and MSDA Track Interests:
	My potential career goal based on my Clifton Strengths is to become a data scientist. 
1.  How My Clifton Strengths and Career Plan Intersect
Data Scientist Relator
My strength as a relator will help me when working closely with other members of the data team and stakeholders to develop solutions that meet the organization’s needs through data-driven solutions. Relating to data engineers, software developers, and other business stakeholders is a necessary skill for a data analyst to have to understand data requirements and to design actionable insights that align with the goals of the organization. 
Belief and Data Science
Belief will help me to persevere and hold to my values when I become overwhelmed or feel inept in my educational and professional journey to become a data scientist. My belief will help me adhere to ethical standards and make me a marketable employee. When working with sensitive data, I will be responsible and trusted to keep data secure. I do not easily succumb to peer pressure. My core values of being dependable, authentic, and trustworthy will help combat temptations to practice anything that is unethical. 
Intellection and Data Science
My strength in intellection will help me to think of things that are not yet known.  Even though I do struggle with creativity, I do have a passion for analyzing information. I will lean on this strength to help me over the hump when needing to be creative in thinking of different questions and datasets that need to be considered when I am needing to come up with actionable insights that will benefit the organization the most. I will also lean on this intellect and love for thinking to help me pick up the intricacies of becoming proficient in Python. Introspection will help me figure out business questions internally if I am left to decide on my own. 
Data Scientist – the Forever Learner
My passion and love for learning will help me to keep up with the latest technology, analytics, and business information to keep relevant in the industry I choose to work in. I do love the process of learning new things, and if I choose the right organization, I can rest assured that the employer would not hire a data scientist who is not interested in stretching their mental schoolhouse. I love to go all in when learning new material and think things through by formulating questions and not giving up until I find the answer. The excitement and satisfaction of learning new things and relaying them to others are rewarding, and this will help me greatly when learning the skills required of a data scientist.
The Deliberative Data Scientist
My strength in being deliberative will help me to not act rashly and without the action being well thought out. I know that obstacles and issues pop up regularly, and I am surprised when this is not the case. Domain knowledge, statistics and probability, and coding all require vigilance and the ability to troubleshoot. With a thorough knowledge of my industry, I will think out all the risks that my organization may face. Probability and coding are both about figuring out the chance of something occurring and computing a way to work through it. 
Conclusion
	The Clifton Strengths assessment is a tool that helps people focus on their strengths over their weaknesses. Reflecting on the results of this assessment is incredibly helpful to me since I am at a disadvantage in starting out in data analytics later in life. I need to be cognizant of my strengths to fight times of self-doubt that I am sure to face. The opportunity to analyze different data analytics roles alongside this self-reflection has affirmed my current aspiration to become a data scientist. In having the knowledge of the advantages and disadvantages of these strengths, I am better equipped to know how to face the challenges in my educational and professional pathway. 

References
Bothma, Joleen. (2023, December 6). How to Become a Business Intelligence Analyst in 2025: 5 Steps for Success. https://www.datacamp.com/blog/how-to-become-a-business-intelligence-analyst
Coursera Staff. (2025, April 8). 7 In-Demand Data Analyst Skills to Get You Hired in 2025. https://www.coursera.org/articles/in-demand-data-analyst-skills-to-get-hired
Coursera Staff. (2025, May 21). 7 Skills Every Data Scientist Should Have. https://www.coursera.org/articles/data-scientist-skills
Crabtree, Matt. (2024, September 28). 9 Essential Data Analyst Skills: A Comprehensive Career Guide. https://www.datacamp.com/blog/data-analyst-skills-for-career-success
NCSU.edu. (accessed July 4, 2025). Online and Distance Education | Information Technology: Business Intelligence Analyst. https://online-distance.ncsu.edu/career/business-intelligence-analyst/
Project Pro. (2024, October 11). Data Science Compared with Different Analytics Disciplines.https://www.projectpro.io/article/data-science-compared-with-different-analytics-disciplines/175#mcetoc_1f9b88scfb
Robinson, E. & Nolis, J. (2020). Build a Career in Data Science. Manning Publications.
US Bureau of Labor Statistics (BLS). (2025, April 18). Occupational Outlook Handbook: Data Scientists. https://www.bls.gov/ooh/math/data-scientists.htm
WGU.edu. (accessed July 6, 2025). D596: The Data Analytics Journey. 
